### PR TITLE
Avoid usage of .instance

### PR DESCRIPTION
**Pull request by jorisdg**
Would love your input in general about an API or APIs we can provide for easy access to some of these objects and data from the D365 tools.

In general avoid usage of any static Instance properties you're seeing. We'll likely be making some of these obsolete as we evolve our Visual Studio tools.

Thanks for your contributions to the community! We need more of this from other people too :-)

### CODE REVIEW

**Comment by TrudAX** [comment]
Thanks for the comments
For API - in general, I liked it, several proposals/questions:
1.Provide some standard documentation about how to create an element and add it to the active project(to the proper folder type)
2.How to call "Apply pattern" function for the form
image
3. It will be nice to have access(inside the Addin code) to the editor, current object and selected text inside the current editor. Also, some API to modify text in the editor(like in EditorScripts for AX2012)
 image
4. I didn't get a concept of classDeclarion method. In the code editor, you don't see it. For AxClass object it is a method ends with "}". 
image
If you want we can also chat via skype: denis_trunin

**Comment by TrudAX** [comment]
Hi Joris. Your code contains CoreUtility.GetService method call, but I don't have this method in my version(it is 8.0 Local One box PU15). So compile is failed with - "'CoreUtility' does not contain a definition for 'GetService'" error
Is it a new method? How it can be replaced in 8.0?

**Comment by xAlexanderKotov** [comment]
I believe you just need to include Microsoft.Dynamics.Framework.Tools.MetaModel.Core.dll to your project.

Under the hood it is probably calls VS standard extension method GetService to get a custom service (or at least this is how it should be done in VS extension).

https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-get-a-service?view=vs-2017

**Comment by TrudAX** [comment]
The problem is that CoreUtility.GetService method is marked as internal
I used AxServiceProvider.GetService instead.

**Pull request merged**
